### ISSUE TITLE
Dynamic ping time adjustment

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-csharp#208]
So @funjack had the great idea to use the ping message as QoS for latency-adjustment. We should also possibly adjust our ping times dynamically based on return timings, so we don't have to constantly guess at the config value.
 
(this is a v0.2 or later thing)

**Comment by blackspherefollower** [comment]
In order for the server to be able to time the round-trip, it must send a message and receive the response. Right now it's just responding to the message received from the client:

client         server
  ---  ping  -->
  <--   ok  ---

This mean that the client can time the loo, but doesn't help the server. We'd likely need to add a pong to the ping to cause a round-trip on the server side:

client         server
  ---  ping  -->
  <-- pong ---
  ---    ok   -->

**Comment by qdot** [comment]
Ping has been disabled by default for just about forever, and no one has really ever asked for this. Closing for now, can revisit if needed once users can set up ping time themselves. Marking WONTFIX.
