### ISSUE TITLE
 Build a simple device enumeration system for testing

### ISSUE THREAD

**Issue by valuta1995** [buttplugio/buttplug-csharp#258]
As per discord mention.

Like "just scan and show us services and characteristics"

So like vibratissiomo's custom name support but even more promiscuous

**Comment by qdot** [comment]
Issue moved to [buttplugio/buttplug-windows-suite #15](https://github.com/buttplugio/buttplug-windows-suite/issues/15) via [**ZenHub**](https://www.zenhub.com/)
