### ISSUE TITLE
Refactor the Controls library so that is doesn't depend on Server

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug-csharp#298]
If you're hoping to use Controls library for client applications you'll still need to depend on the server libraries too, as the ButtplugTab is an IButtplugServerFactory.

Refactoring this will be non-trivial, as the current  depend on this.

**Comment by qdot** [comment]
Issue moved to [buttplugio/buttplug-windows-suite #21](https://github.com/buttplugio/buttplug-windows-suite/issues/21) via [**ZenHub**](https://www.zenhub.com/)
