### ISSUE TITLE
Suggestions for improving the scan function

### ISSUE THREAD

**Issue by bnm12** [buttplugio/buttplug-csharp#330]
Currently the scan function quickly passes instant devices such as XInput devices and never revisits them, and keeps scanning for BLE devices forever. 
This has the following consequences: 

1. The ScanningFinished event is never fired as the scan never actually finishes 
2. If you want to rediscover a lost XInput device you have to keep calling scan to make it recheck causing the BLE scan to get cut short

My suggestions for the direction of the method are:

1. Allow for an optional timeout value to get passed to the StartScan method, when timeout is reached stop the scan and fire the ScanningFinished event. If timeout is not set scan forever or until the StopScan method is called (whichever comes first) then fire the ScanningFinished event
2. Make the Scan continuously poll for XInput and other instant devices (X ms interval) for the duration of the scan
3. Allow for an optional parameter to the StartScan (and StopScan) method specifying which modules to start/stop the scanning of for greater control e.g. if you are done searching for XInput but want to keep looking for something else, or the other way around

**Comment by qdot** [comment]
So I realize this isn't exactly a duplicate, but this is getting fixed in #567 using option 2, so I'm gonna go ahead and close for now. Option 1/3 aren't really viable because I ruled out in-library timeouts in #335.
