### ISSUE TITLE
SerialPort Scanning Crash

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-csharp#333]
https://sentry.io/metafetish/buttplug-csharp/issues/436613366/

```
IOException: I/O-åtgärden har avbrutits därför att en tråd har avslutats eller för att ett program har begärt det.

  Module "Buttplug.Server.Managers.ETSerialManager.ETSerialManager", line 209, in ScanSerialPorts
    Void ScanSerialPorts(System.String[])
  Module "Buttplug.Server.Managers.ETSerialManager.ETSerialManager", line 0, in StartScanning { <lambda> }
    Void <StartScanning>b__4_0()
...
(7 additional frame(s) were not displayed)

I/O-åtgärden har avbrutits därför att en tråd har avslutats eller för att ett program har begärt det.

```

**Comment by blackspherefollower** [comment]
Translation from Swedish:
IOException: The I / O operation has been interrupted because a thread has been terminated or for a program has requested it.

**Comment by blackspherefollower** [comment]
https://ci.appveyor.com/project/qdot/buttplug-csharp/build/0.1.3.574
https://github.com/metafetish/buttplug-csharp/commit/d589b2f1e98963a6a6f61b8caeaed69f53b670ac

**Comment by qdot** [comment]
Haven't seen this crash again since, closing for now.
