### ISSUE TITLE
Restructure the way the device commands are sent

### ISSUE THREAD

**Issue by bnm12** [buttplugio/buttplug-csharp#350]
Currently to send command like e.g. the VibrateCmd you have to send as follows:

```CSharp
_client.SendDeviceMessage(device, new VibrateCmd(device.Index,
                            new List<VibrateCmd.VibrateSubcommand>() {
                                new VibrateCmd.VibrateSubcommand((uint)featureId, speed) })));
```

Here  it seems quite unnecessary to both send the full device object and then in the command also send the device index from the same object.
In my opinion SendDeviceMessage should either *not* take a device as a parameter and solely rely on the information in the Cmd object. Or SendDeviceMessage does take a device as input and then the Cmd doesn't as those will be autofilled from the device object before sending them to the server.

All of this is assuming that there is no legitimate use for providing a device as the first parameter and then providing the index for a different device in the Cmd.

If implemented as suggested it will still look mostly the same, but it will be easier to type, less confusing, and less error prone in the case where you accidentally specify a wrong device index in the Cmd
```CSharp
_client.SendDeviceMessage(device, new VibrateCmd(
                            new List<VibrateCmd.VibrateSubcommand>() {
                                new VibrateCmd.VibrateSubcommand((uint)featureId, speed) })));
```

This should be changed for all variations of Cmd objects if this happens in other places too

**Comment by qdot** [comment]
Marking INVALID, as this got redesigned in 26d448f1037a3bfaf7a8b17a05526e2952956271. Devices now hold references to their owning clients, and have their own "SendMessageAsync" function. That way, the device can provide the extra context that the client needs for filling out messages, and the API makes it look like the user is addressing the device directly.
