### ISSUE TITLE
Mouse location/movement Launch control

### ISSUE THREAD

**Issue by g-coded** [buttplugio/buttplug-csharp#385]
Feature request to allow direct control of launch location using mouse pointer speed/location/direction(y-axis), can't find anything outside of Android apps.

**Comment by qdot** [comment]
Ok, so you're wanting to be able to move the mouse pointer up and down and have the launch approximate that movement? From what we were talking about on reddit, I thought you wanted sort of the opposite (we move launch, and as we're doing so we also make fake mouse events so the movement in a game matches the movement of the launch).

**Comment by g-coded** [comment]
Any progress on this?  I see you've been busy and didn't want to pry.

**Comment by qdot** [comment]
Issue moved to [buttplugio/buttplug-windows-suite #19](https://github.com/buttplugio/buttplug-windows-suite/issues/19) via [**ZenHub**](https://www.zenhub.com/)

**Comment by qdot** [comment]
Moving this over to the windows-suite for now, since this repo isn't really for application work anymore. Still not quite sure where this would get implemented.
