### ISSUE TITLE
Clean up Lovense message initliaization

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-csharp#439]
Lovense devices initialize their message handlers in the constructor, then change them in the Initialize function for Edge and Nora cases. We can probably just do all of the setup in Initialize now and keep all of the logic in the same place.

**Comment by hiss-remi** [comment]
While we're at it, is it just me or is there no way to control the air function on Max at all?

**Comment by qdot** [comment]
@hiss-remi Hah, we're missing a list of features of Lovense toys.

- Can't set air pressure in Max
- Can't set LEDs on Domi
- Can't access built-in patterns on toys

For the Max and inflation specifically, we've talked about it some in terms of generic messages (i.e. do we need an inflate/constrict message or something?). We didn't get real far, and I opted to punt on it until the system had some time to stablize and we could iterate on APIs, as I didn't want to end up with a massively opinionated system that only I had experience with and input on. That's been a rather slow process though.

Also, the aforementioned conversations unfortunately happened on either slack or discord, which is why I'm trying to push for RFP issues over on the buttplugio/buttplug repo now, so I can just point there.

**Comment by hiss-remi** [comment]
"Inflate" sounds like a reasonable name that could also fit devices that expand* rather than constrict. ... Is that a good thing?

*Admittedly not sure I'd want to try it even if I ran into such a thing that was bluetooth controlled.

**Comment by qdot** [comment]
Yeah, I'll add another RFP bug to the Buttplug repo about it (as this bug is about something different anyways), will ping you on it.

**Comment by hiss-remi** [comment]
I thought I'd knock this one out quick, but it looks like I did something wrong in the process, because it seems to want to smoosh together the last four commits to the main repository in with the bit that's actually new.

**Comment by qdot** [comment]
@hiss-remi Looks like there was a merge issue on your master branch of your buttplug-csharp repo, and it changed the hashes of the last 4 commits before your HEAD (even though I think they're the same content in the commits). You might be able to do a git rebase against the buttplugio master which may clear it up and then you could PR, or if you'd like, the commit looks fine, so I could bring your commit in directly and then you could just reset your master to the state our master is in after it's finished.

Isn't git fun. \o/

**Comment by hiss-remi** [comment]
I'm fine with the latter, as long as you can tell me how to do this "reset your master" thing, because I'm lost. I don't get git at all...

**Comment by qdot** [comment]
Done as part of #441, landed in #457. Thanks @hiss-remi!
