### ISSUE TITLE
Add Wevibe Classic name

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-csharp#444]
See https://metafetish.club/t/cannot-find-we-vibe-classic-in-buttplug-server/345/5

@blackspherefollower The name "classic" is in our code, but the name being seen on the toy is "Classic". Did your test of this show something different?

**Comment by blackspherefollower** [comment]
I think that was based on theOne's work: I guess this means that the BLE names were being thrown though tolower before comparison.

There are other names in the list that come from other sources too. The only devices I've personally tested are the pivot and verge.

**Comment by qdot** [comment]
This landed, don't know what it wasn't resolved then.
