### ISSUE TITLE
Make WPF projects inherit dependencies from .Net Standard projects

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-csharp#464]
The new .Net Standard project style doesn't currently share dependencies/references with the WPF apps, meaning references have to be added multiple times. There's a flag to fix these that needs to be added to the projects to make sure this doesn't keep happening, as it will get really nasty on the next release otherwise.

**Comment by qdot** [comment]
This needs to be added to the .csproj file of any .Net Framework project that depends on the .Net Standard libraries.

```
<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
```

It may also be worth just re-implementing the .Net Framework targets for the standard projects, as this extra step may be too much for some users.

**Comment by blackspherefollower** [comment]
How much of an issue is that, given that most users will consume the NuGet rather than reference the projects from source?

**Comment by qdot** [comment]
That's where the "may also" came from. I don't know if this only happens in projects local to the library projects, or across NuGet too.

**Comment by qdot** [comment]
Closing was WONTFIX. This doesn't actually work very well yet, and really confuses Appveyor. It's also only a problem when having multiple projects inside the same solution. Nuget packages with dual Framework/Standard output are fine.
