### ISSUE TITLE
Improve GUI testing

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug-csharp#469]
We've seen the cirrent tests for the GUIs can't be trusted, so maybe a standalone system test would be better?

Fom https://blog.testproject.io/2016/12/22/open-source-test-automation-tools-for-desktop-applications/ White and Winiam look promising.

**Comment by qdot** [comment]
Issue moved to [buttplugio/buttplug-windows-suite #22](https://github.com/buttplugio/buttplug-windows-suite/issues/22) via [**ZenHub**](https://www.zenhub.com/)
