### ISSUE TITLE
Some users have failures trying to read/write to Roaming

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-csharp#476]
Just had a user on discord who couldn't start the websocket server with SSL because the cert wasn't showing up. Turns out, they had no c:\Users\[name]\AppData\Roaming\Buttplug directory. If they run as admin, it showed up. We need to figure out a way to create configuration that's robust enough to deal with a situation where a user can't creating Roaming data. Also need to figure out why a user can't create Roaming data in the first place.

**Comment by blackspherefollower** [comment]
Did the server still fail to generate the cert even after creating the directory?

I know that there's a mkdir missing from the config writer code, but normally the cert code gets there first and creates the folder (except when that exception handling was missing in master a bit ago).

Also, any environment information? Any particular virus scanners or similar that could be augmenting the ACLs?

**Comment by qdot** [comment]
Windows 10 build 17xxx. Didn't ask about virus scanners, though this happened on the #buttplug-support channel on discord so you can see the log there.

I had them create the directory themselves. At that point, the config file wrote but the cert still wouldn't. Running as administrator made everything work.

**Comment by blackspherefollower** [comment]
I'm wondering if it might be related to the anti-randomware stuff Windows introduced recently. I found it was disabled on at least one of my systems by default, so I'll try and play with that.

**Comment by qdot** [comment]
Issue moved to [buttplugio/buttplug-windows-suite #2](https://github.com/buttplugio/buttplug-windows-suite/issues/2) via [**ZenHub**](https://www.zenhub.com/)
