### ISSUE TITLE
Fix Lovense device connection; detects device but fails to connect

### ISSUE THREAD

**Issue by ToxicHax** [buttplugio/buttplug-csharp#528]
Lovense device can be detected but refuses to connect and throws a 'null read' error:

`[Error] Got null read from LVS-B011`
`[Error] Cannot connect to device LVS-B011 81672069427: Got null read from LVS-B011`

Must be an issue with this pre-release version
Also tested it by running a v2.3(stable) buttplug server which connects the device just fine.

_Version: prerelease - v0.2.3.840
Device: Lovense Max (6th gen)
Windows 10 (ver 1803 - build: 17134.345)
.Net 4.7.1_

**Comment by qdot** [comment]
Gonna dup this against #417, which wasn't actually fixed. Actually fixing #417 fixes this.
