### ISSUE TITLE
Update device protocols for external config loading

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-csharp#654]
Once we can load message attributes from the device config file (buttplugio/buttplug-device-config#8), we need to:

- add identification setting to all protocols
- generalize message handlers to deal with taking FeatureCount from device config

I'm not sure if there's much to do with StepCount, as that's more for guidance on the client side.

Also, this is all getting rewritten in Rust sometime (hopefully soon?), so I'm really not sure exactly how much time should be spent on this.

**Comment by qdot** [comment]
@blackspherefollower This one is all yours after the device config updates are done if you want it. Should happen on the `spec-v2` branch.

**Comment by blackspherefollower** [comment]
I should have some time this week to get stuck in. Not sure how much I'll be online over the holiday weeks though.

**Comment by qdot** [comment]
Moving to client only impl.
