### ISSUE TITLE
 Support for Kiiroo Onyx + (plus)

### ISSUE THREAD

**Issue by WrobelK** [buttplugio/buttplug-csharp#658]
Please add support for Kiiroo Onyx + (plus)

**Comment by blackspherefollower** [comment]
Cross-referencing https://metafetish.club/t/adding-new-kiiroo-onyx-plus-for-service-in-buttplug-intiface-and-buttplug-java/1035/

**Comment by qdot** [comment]
Added in buttplug-rs, just landed, closing this as it'll be working via the FFI.
