### ISSUE TITLE
Concurrent access exception thrown by ButtplugClient

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug-csharp#664]
Unfortunately I lost the log, but whilst testing the Xamarin examples I hit an issue where _devices is modified during access, resulting in an exception.

I believe multiple Vibratissimo devices advertised at the same time and managed to clash: not a race condition I've been able to reproduced since hitting it 3 times in a row.

**Comment by qdot** [comment]
Not sure if this'll happen now that we're client only, but I merged the PR so closing.
