### ISSUE TITLE
Xamarin Assembly Scanning is Unsupported

### ISSUE THREAD

**Issue by narcoticpopcorn** [buttplugio/buttplug-csharp#667]
I ran into a hiccup getting started, it may be nice to specify in the docs, or with a friendly exception, that a DeviceSubtypeManager must be specified in Xamarin. The assembly scanning code errors out with what looks like a file permission error but is actually just unsupported behavior. I also think dynamic loading of assemblies is against TOS for IOS and possibly unsupported in general.

Working example
``` csharp
var connector = new ButtplugEmbeddedConnector("Embedded Server");
// Without this line (or one like it specifying a subtypemanager), StartScanningAsync will error out with an UnauthorizedException
connector.Server.AddDeviceSubtypeManager((lm) => new XamarinBluetoothManager(lm));
Client = new ButtplugClient("Embedded Client", connector);
```

**Comment by qdot** [comment]
Ugh, scanning bites us again.

BTW, a heads up, the C# library is going to be an FFI shim on top of Rust soon. I'm *hoping* I can still support xamarin that way, but things may get a bit bumpy for a while.

**Comment by qdot** [comment]
Moving to client only impl. Marking wontfix and closing.
