### ISSUE TITLE
Finish notification characteristic implementation for the launch

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-csharp#67]
Hopefully creating the notification characteristic for the Fleshlight Launch will alleviate some of the issues we're having with the Launch disconnecting while idle.

**Comment by blackspherefollower** [comment]
@qdot Was this the issue caused by the power saving mode on your BLE dongle?

**Comment by qdot** [comment]
This was caused by a shitty dongle 3 years ago and should've been closed then. Oops.
