### ISSUE TITLE
Not returning correct device in RemoveDevice event when device is disconnected

### ISSUE THREAD

**Issue by sirogane730** [buttplugio/buttplug-csharp#683]
sorry for the machine translation.
I am using Buutplug Unity v3.0.
I seem to have a problem with the behavior of RemoveDevice event.

(1)Start Interface-central
(2)Run StartServerProcessAndScan in Unity to connect with Interface-central 
(3)connected Volze A10 CycloneSA 
(4)connected Lovnese edge
(5)Disconnected Lovnese edge
(6)CycloneSA is judged to be disconnected by Unity's RemoveDevice event
　(Lovnese edge is judged as disconnected on Interface-central)
If I am using something wrong, please point it out to me.
Version used is Unity 2021.3.16f1
![2023-05-10_004650](https://github.com/buttplugio/buttplug-unity/assets/86196211/29919632-626b-457c-a384-1be81b1cf376)

**Comment by qdot** [comment]
Ok this is actually a bug in the C# library, moving it over there. I've repro'd locally and am getting this fixed up now.

**Comment by qdot** [comment]
Ok, this ended up being an error in our DeviceRemoved message parsing in the v3 series. It'll be fixed in v3.1, hopefully out this week. I'll be releasing an update of the Unity plugin with that.
